# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (c) 2026 BayLibre, SAS
#
# Author: Julien Stephan <jstephan@baylibre.com>

obj-$(CONFIG_VIDEO_MEDIATEK_HDMI) += \
	mtk_disp_comp.o \
	mtk_disp_merge.o \
	mtk_disp_mutex.o \
	mtk_disp_padding.o \
	mtk_dpi.o \
	mtk_ethdr.o \
	mtk_hdmi.o \
	mtk_mdp_rdma.o \
	mtk_smi_larb.o
