# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (c) 2026 BayLibre, SAS
#
# Author: Julien Stephan <jstephan@baylibre.com>

obj-$(CONFIG_VIDEO_MEDIATEK_DISP_COMMON) += \
	mtk_disp_comp.o \
	mtk_disp_mutex.o

obj-$(CONFIG_VIDEO_MEDIATEK_HDMI) += \
	mtk_disp_merge.o \
	mtk_disp_padding.o \
	mtk_dpi.o \
	mtk_ethdr.o \
	mtk_hdmi.o \
	mtk_mdp_rdma.o \
	mtk_smi_larb.o

obj-$(CONFIG_VIDEO_MEDIATEK_VDOSYS0) += \
	mtk_ddp.o \
	mtk_disp_ovl.o \
	mtk_disp_rdma.o \
	mtk_smi.o

obj-$(CONFIG_VIDEO_MEDIATEK_DSI) += \
	mtk_disp_aal.o \
	mtk_disp_ccorr.o \
	mtk_disp_color.o \
	mtk_disp_dither.o \
	mtk_disp_gamma.o \
	mtk_dsi.o \
	mtk_dsi_host.o \
	mtk_mipi_tx.o
