# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_OPTEE) += core.o
obj-y += supplicant.o
obj-$(CONFIG_DM_I2C) += i2c.o
obj-$(CONFIG_SUPPORT_EMMC_RPMB) += rpmb_emmc.o
obj-$(CONFIG_SUPPORT_UFS_RPMB) += rpmb_ufs.o
